- name: ScaleIO deployment
  hosts: scaleio
  tasks:
    - name: Copy ScaleIO rpm files
      copy:
        src: /root/{{ item }}
        dest: /root/ 
      with_items:
        - 'EMC-ScaleIO-lia-2.5-0.254.el7.x86_64.rpm'
        - 'EMC-ScaleIO-sds-2.5-0.254.el7.x86_64.rpm'
        - 'EMC-ScaleIO-mdm-2.5-0.254.el7.x86_64.rpm'
        - 'EMC-ScaleIO-sdc-2.5-0.254.el7.x86_64.rpm'

    - name: Install ScaleIO rpm files
      environment:
        TOKEN: 'P@ssw0rd'
      yum: 
        name: "{{ item }}"
        state: installed
      with_items:
        - '/root/EMC-ScaleIO-lia-2.5-0.254.el7.x86_64.rpm'
        - '/root/EMC-ScaleIO-sds-2.5-0.254.el7.x86_64.rpm'

- name: ScaleIO install mdm primary master
  hosts: scaleio-install-mdm12
  environment:
    MDM_ROLE_IS_MANAGER: 1
  tasks:
    - name: ScaleIO install mdm primary master
      yum: 
        name: "{{ item }}"
        state: installed
      with_items:
        - '/root/EMC-ScaleIO-mdm-2.5-0.254.el7.x86_64.rpm'
        - '/root/EMC-ScaleIO-mdm-2.5-0.254.el7.x86_64.rpm'
       


- name: ScaleIO install mdm tie breaker
  hosts: scaleio-install-mdm-3
  environment:
    MDM_ROLE_IS_MANAGER: 0 
  tasks:
    - name: ScaleIO install mdm tie breaker
      yum: 
        name: /root/EMC-ScaleIO-mdm-2.5-0.254.el7.x86_64.rpm 

- name: ScaleIO cluster configuration
  hosts: scaleio-sio-configuration
  environment:
    SDS1DATAIPS: '192.168.2.201,192.168.3.201' 
    SDS2DATAIPS: '192.168.2.202,192.168.3.202'
    SDS3DATAIPS: '192.168.2.203,192.168.3.203'
    SDS4DATAIPS: '192.168.2.204,192.168.3.204'
    SDS1MGMTIP: '192.168.0.201'
    SDS2MGMTIP: '192.168.0.202'
  tasks:
    - name: ScaleIO cluster configuration
      shell: | 
        scli --create_mdm_cluster --master_mdm_ip "$SDS1DATAIPS" --master_mdm_management_ip "$SDS1MGMTIP" --master_mdm_name mdm1 --accept_license --use_nonsecure_communication
        sleep 7 
        scli --login --username admin --password admin --approve_certificate
        scli --set_password --old_password admin --new_password P@ssw0rd 
        scli --login --username admin --password P@ssw0rd --approve_certificate
        sleep 5
        scli --add_standby_mdm --new_mdm_ip "$SDS2DATAIPS" --mdm_role manager --new_mdm_management_ip "$SDS2MGMTIP" --new_mdm_name mdm2
        sleep 6
        scli --add_standby_mdm --new_mdm_ip "$SDS3DATAIPS" --mdm_role tb --new_mdm_name tb 
        scli --switch_cluster_mode --cluster_mode 3_node --add_slave_mdm_name mdm2 --add_tb_name tb 
        
        sleep 8
         
        scli --add_protection_domain --protection_domain_name PD1
        scli --add_storage_pool --protection_domain_name PD1 --storage_pool_name POOL1

        scli --set_performance_parameters  --all_sds --all_sdc --apply_to_mdm --profile high_performance
        scli --rename_system --new_name SIOSYSTEM
        sleep 10

        scli --login --username admin --password P@ssw0rd --approve_certificate
        scli --add_sds --sds_ip "$SDS1DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds1
        sleep 15
        scli --add_sds --sds_ip "$SDS2DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds2
        sleep 15
        scli --add_sds --sds_ip "$SDS3DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds3
        sleep 15
        scli --add_sds --sds_ip "$SDS4DATAIPS" --device_path /dev/sdb --protection_domain_name PD1 --storage_pool_name POOL1 --sds_name sds4
